version: '3.8'

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    restart: always
    volumes:
      - data:/data
      - ./config.yml:/config.yml
    environment:
      - TZ=Etc/UTC
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=10
      - DIUN_WATCH_SCHEDULE=0 13 * * *
      - DIUN_PROVIDERS_FILE_FILENAME=config.yml
      - DIUN_NOTIF_TELEGRAM_TOKEN
      - DIUN_NOTIF_TELEGRAM_CHATIDS

volumes:
  data: